# Generated by Django 4.0 on 2021-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('estados', models.CharField(max_length=30)),
                ('alfabeto', models.CharField(max_length=10)),
                ('estado_inicial', models.CharField(max_length=1)),
                ('estados_aceitacao', models.CharField(max_length=10)),
                ('tabela_transicao', models.CharField(max_length=30)),
            ],
        ),
    ]
