# Generated by Django 4.0 on 2021-12-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=70)),
                ('estados', models.CharField(max_length=30)),
                ('alfabeto', models.CharField(max_length=10)),
                ('alfabeto_fita', models.CharField(max_length=10)),
                ('estado_inicial', models.CharField(max_length=1)),
                ('halt_accept', models.CharField(max_length=10)),
                ('halt_reject', models.CharField(max_length=10)),
                ('tabela_transicao', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='automato',
            name='descricao',
            field=models.CharField(max_length=70),
        ),
    ]
