# Generated by Django 4.0 on 2021-12-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0002_maquina_alter_automato_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.CharField(max_length=20)),
            ],
        ),
    ]
